#!/bin/sh
echo "Downloading packer..."
git clone --depth 1 https://github.com/wbthomason/packer.nvim\
 ~/.local/share/nvim/site/pack/packer/start/packer.nvim

echo "Copying settings..."
cp -r .config/nvim $HOME/.config/nvim

